Make frontmatter extraction not rely on variable scope or temp files.

diff --git a/marsh b/marsh
--- a/marsh
+++ b/marsh
@@ -1037,7 +1037,9 @@ function marsh_has_frontmatter {  # marsh_has_frontmatter source
 
 # extracts yaml frontmatter and document content
 function marsh_extract_frontmatter {  # marsh_extract_frontmatter source meta_dest content_dest
-    local SOURCE META_DEST CONTENT_DEST META_TEMP CONTENT_TEMP
+    local SOURCE META_DEST CONTENT_DEST
+
+    # init
     SOURCE="${1:-}"
     META_DEST="${2:-}"
     CONTENT_DEST="${3:-}"
@@ -1045,13 +1047,16 @@ function marsh_extract_frontmatter {  # marsh_extract_frontmatter source meta_de
     [[ "${META_DEST}" == "" ]] && return 1
     [[ "${CONTENT_DEST}" == "" ]] && return 1
 
-    META_TEMP=$(mktemp "${MARSH_TEMP}/document-meta-XXXXXX") || return 1
-    CONTENT_TEMP=$(mktemp "${MARSH_TEMP}/document-content-XXXXXX") || {
-        rm -f "${META_TEMP}"
+    # prepare output files
+    rm -f "${META_DEST}" "${CONTENT_DEST}"
+    : > "${META_DEST}" || return 1
+    : > "${CONTENT_DEST}" || {
+        rm -f "${META_DEST}"
         return 1
     }
 
-    awk -v meta_out="${META_TEMP}" -v content_out="${CONTENT_TEMP}" '
+    # extract frontmatter and content
+    awk -v meta_out="${META_DEST}" -v content_out="${CONTENT_DEST}" '
     NR == 1 {
         if ($0 ~ /^---[ ]*(#.*)?$/) {
             have_yaml = 1
@@ -1083,20 +1088,13 @@ function marsh_extract_frontmatter {  # marsh_extract_frontmatter source meta_de
             print "..." >> meta_out
         }
     }' "${SOURCE}"
-    if [[ "$?" -ne 0 ]]; then
-        rm -f "${META_TEMP}"
-        rm -f "${CONTENT_TEMP}"
+
+    # clean up on failure
+    if [[ "$?" -ne 0 ]] || [[ ! -f "${META_DEST}" ]] || [[ ! -f "${CONTENT_DEST}" ]]; then
+        rm -f "${META_DEST}" "${CONTENT_DEST}" 2>/dev/null
         return 1
     fi
-    mv "${META_TEMP}" "${META_DEST}" || {
-        rm -f "${META_TEMP}"
-        rm -f "${CONTENT_TEMP}"
-        return 1
-    }
-    mv "${CONTENT_TEMP}" "${CONTENT_DEST}" || {
-        rm -f "${CONTENT_TEMP}"
-        return 1
-    }
+
     return 0
 }
 
