Make temporary directory creation more robust.

diff --git a/marsh b/marsh
--- a/marsh
+++ b/marsh
@@ -2221,7 +2221,13 @@ mkdir -p "${MARSH_CONFIG_PATH}"
 # keep temporary directory creation close to trap to catch quick SIGINT
 # temporary directory
 if [[ "${MARSH_UID:-}" == "" ]]; then
-    MARSH_TEMP=$(mktemp -d "${TMPDIR:-/tmp/}marsh-XXXXXX")
+    TEMP_DIR="${TMPDIR:-/tmp}"
+    TEMP_DIR="${TEMP_DIR%/}"
+    MARSH_TEMP=$(mktemp -d "${TEMP_DIR}/marsh-XXXXXX" 2>/dev/null)
+    if [[ ! -d "${MARSH_TEMP}" ]]; then
+        echo "Unable to create temporary directory: ${TEMP_DIR}/marsh-XXXXXX" >&2
+        exit 1
+    fi
     MARSH_UID="marsh-${MARSH_TEMP##*marsh-}"
     #export MARSH_TEMP MARSH_UID
 fi
